import "./globals.css";
import { Urbanist } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Urbanist({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin-ext"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body
        className={`bg-zinc-950 selection:bg-indigo-500 selection:text-white ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
